apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: bootcampapp-r6q0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bootcampapp-r6q0
    app.kubernetes.io/part-of: uthtest2
  name: bootcampapp-r6q0
  namespace: utherp0-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: bootcampapp-r6q0
    weight: 100
status: {}
